### ISSUE TITLE
Use the default value for the GitHub token

### ISSUE THREAD

**Issue by EndBug** [instantish/notion-github-action#44]
<sub>[Discuss in #**public-issue-44--using-the-default-value-for-the-github-token**](https://slack.com/app_redirect?team=TJ5G67VHU&channel=C02RL3GDMK5)</sub>

As of now, the user is required to pass the GitHub token to the action through the `github-token` input.
Unless they have restricted the access of the default `GITHUB_TOKEN` in such a way that doesn't allow it to access issues, this value will almost always be the `secrets.GITHUB_TOKEN`.

We could set this value to be the default token inside the action manifest so that the vast majority of users can avoid using this input.
Of course, if they have to use a custom PAT they can always use the input as usual. The docs would need to say that there's this input, but it's only intended to be changed for who needs to use a custom PAT...

What do you think about it? Should I open a PR?

**Comment by marissamarym** [comment]
sounds good, yep let's use the `secrets.GITHUB_TOKEN` by default. I think in the vast majority of cases, they would just want to use that one, but seems nice to still give them the option of using a different PAT. Just because maybe they'd want to generate one with a really reduced permission set, or generate one per action

**Comment by EndBug** [comment]
Sure, I'll open a PR 👍
